### PR TITLE
[FEAT]Emulator Creator, Emulator Configuration, Emulator flow

### PR DESCRIPTION
**Pull request by DeerajTheepshi**
# What :
- This PR features the all new emulator creation flow
- It also features Run Configuration menu item , from where users can select their SDK Platform, select their Emulator (if they have more than 1) .
- Users can also delete or create a new AVD from the Run Configuration window

# Why :
- To give users the choice of running their sketch on different emulator screens. 
- To give users the choice to name, create, configure and delete their emulators. 
- To allow users to make use of different platforms that they download from the SDK Updater .

# How :
- New UI is handled by two classes : CreateAVD.java (The entire flow) and RunConfiguration.java (The menu item) : These two classes are pure UI classes and handle only the corresponding UI.
- New methods to enable are created in AVD.java - This class has some unwanted code that will be removed in further commits.
- The image downloader class - SysimageDownloader.java -  This class was modified to download the selected image, rather than the always default image.
- Emulatorcontroller.java - This class was modified to start the emulator from the given name, rather than starting the default one.

# Note :
- Swing worker has not yet been implemented. (Following commits will do it) **(Completed with d347fd196fd75e4d713dd3cac44d350e643f4dcf)**
- Unwanted code to be remove. **(Completed with dda764d6d914f74ca80f8f4f173a35351df052f7)**
- Add listener to table, so that delete button is enabled only after clicking an item in the table
- Handle back button in create avd windows. **(Completed with d347fd196fd75e4d713dd3cac44d350e643f4dcf)**

# Commit info : 
- Device selector added using : e1165a2c85bf618dcb365005f991987a50a15d61
- What does this do ? Now devices can be selected from the run configuration , just like how you select emulators

# Testing Guidelines : 
- Remove everything related to android emulator from the preferences file. 
- Open processing and select 1.Android >> Run Configurations where you can create new emulators or choose existing ones. 2. You can directly click run on emulator to prompt for new emulator creation.
- **Option 1**
    - Select your Target SDK. A list of all your available SDKs will be shown.
    - Hit create button to go through the process of creating a new emulator.
    - After new emulator is created, you can delete or select and run your sketch on it.
    - Choose the devices radio button to select your device. If no device is found the button will automatically shift back to emulator radio button.
    - During delete option, the UX goes into a minor waiting state, during which message is displayed on the console and after deleting , the table is again refreshed.
- **Option 2**
     - This walks you through a new emulator creation process
     - First fill in your device name , and pick a emulator (phone or wear) , and then a phone device of your choice.
     - After this, the UX goes into loading state, while it is querying for system images in the background. Once query is completed, it presents you with a table of system images.
     -  The already installed system images are shown on top of the table, these can be selected and next button be pressed.
     - If the system image you want is not installed, then click the Download button to download the System-image. Once download is complete via a simple progress bar, , reselct the image and hit next button.
     - This is the final step, confirm your emulator. Emulator creation might take some time. After which the build process will continue. 
      - **Note : ** in case of create button in Run configuration window mention in option 1, the same steps follow.
- **NOTE: ** In either of the cases, the newly created emulator or the selected emulator will be saved and used for future sketch runs. 
- Test deleting the Emulator : Try deleting the previously selected emulator via Run Configuration or through command line using avdmanager. Open processing and choose run . This time processing will detect that the saved emulator is no longer present and will stop the run process and inform you to change the emulator in run configuration window.

### CODE REVIEW

**Comment by kfrajer** [comment]
To clarify your final note in your PR, "the newly created emulator or the selected emulator will be saved and used for future sketch runs", does Processing remember if a full Processing is restarted (close down and re-opened)?

**Comment by kfrajer** [comment]
I run into the following issue when following **option 2** above: When I selected and downloaded a system image, everything worked as expected. However, the new image was not made available in the list as it was not refreshed. I have to close the flow and restart the flow of adding a new emulator again. When I arrived to the step of images available, I was able to see it this time (See image below).  

**SECOND issue**: This window shows images installed and not installed. In the image below, I noticed 21 and 26 shows as "Installed" but they are also listed as "Not installed" (I had to scrolled down the list to see them). Expected behavior: If an image is installed, then it should not be shown as "not installed" as well.

choosing-emu-image.

**Comment by kfrajer** [comment]
For future consideration: *Run configuration* should be renamed to reflect functionality more clearly. I have not had the chance to test actual devices, but it could be called "Manage Devices". It is also important to consider the access point of this in the PDE menu. In the current version, devices and emulators are managed via menu entry point in the PDE: "Android >> Devices".

**To do:** Evaluate final entry point in the PDE menu

**Comment by kfrajer** [comment]
Tested so far:
* Tested flow of running emulator (Emulator did not run. More details below)
* Adding different emulators
* Deleting emulators
* Adding images during the emulator creation flow

Updated https://github.com/processing/processing-android/issues/541 to reflect this effort.

**Comment by kfrajer** [comment]
@DeerajTheepshi Can you comment in the following topics:
1. Are you offering an option to create a default emulator? That is, a simple workflow for new users
2. How are you deciding where to install your emulator's files? I noticed they are being installed in C:\Users\c\.Android\avd path. However, I have already setup previous emulators in another drive: D:\Users\c\.Android\avd and the PDE Android mode are not seeing these ones. 
3. Are you assigning different ports to the emulators when they are launched or are they launched with the same port?
4. What would I expect to happen if I am running one emulator and I were to run "Run Configuration" again to choose another emulator - and run it? I am looking for for a description of what you ahve tested on your side to see if we need to manage this scenario. In AS, you can run multiple emulators but AS will only interact with the most recent launched emulator so the user will need to manage any existent loaded emulator. FYI, I have not been able to run an emulator as yet.

**Comment by kfrajer** [comment]
While testing creating devices, I am using the avdmanager CLI and the avdmanager UI from AS as a cross-reference. From my initial testing, they cannot see the newly created devices using the PDE's "Run Configuration" flow. This is my current setup that I have in my D: drive while initially managing emulators using AS:
1. a nexus5
2. a Pixel XL
3. Processing-phone

After I run the "Run Configuration" flow and after creating a coupled of emulators, I get the following in my C: drive from the PDE flow:

1. emu-alpha
2. emu-beta
3. Processing-phone

Both avdmanager CLI and UI (from AS) only shows nexus5, Pixel XL and Processing-phone. However, it seems the Pixel XL is corrupted as well as the Processing-phone as you can see in the image below.  I am also *unable* to run a sketch in any of the recently created devices (tried both emu-alpha and emu-beta NOTE: Processing-phone is not in the list) but it did not work. I get the following error (screenshot at the end):

> Emulator process exited with status 1.
> EmulatorController: Emulator never booted. NOT_RUNNING
> Error while starting the emulator. (NOT_RUNNING)
> Shutting down any existing adb server... Done.

fail-emu-processing-phone

PDE-emulator-doesnot-launched
):

**Comment by kfrajer** [comment]
These are two commands I am using for reference:

In the emulator folder: `emulator -list-avds`
In the tools/bin folder: `avdmanager list avd`

In both above commands, I can see the emulators that I have previously setup but none of the emulators created by the PDE flow. 

Reference [link](https://stackoverflow.com/questions/4974568/how-do-i-launch-the-android-emulator-from-the-command-line) from StackOverflow

@DeerajTheepshi  Can you discuss your strategy when adding the emulators? I can look into this on my side.

**Comment by DeerajTheepshi** [comment]
I have moved all these into issues. Take a look into them @kfrajer

**Pull request merged**
